---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nguyen95/public_html/
    - /bin/cp ./build/* $DEPLOYPATH
    - /bin/cp -R ./build/static/css $DEPLOYPATH
    - /bin/cp -R ./build/static/js $DEPLOYPATH
    - /bin/cp -R ./build/static/media $DEPLOYPATH